#!/bin/bash

DEBUG=${DEBUG:-0}

LOGFLAGS="--reverse --ancestry-path --no-abbrev-commit --pretty=oneline"
DEPFLAGS=""

if [ $DEBUG -ne 0 ]; then
  DEPFLAGS="-d"
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
EARLIEST=$(git log master..$BRANCH $LOGFLAGS | head -n 1 | cut -d ' ' -f 1)
LATEST=HEAD

function stderr {
  echo "$@" >&2
}

if [[ -z "$EARLIEST" ]]; then
  stderr "No commits within branch. Refusing to fixup commits within master branch."
  exit 1
fi

if git diff --cached --quiet; then
  stderr "No staged changes."
  stderr "help: You need to stage some changes with `git add` first."
  exit 1
fi

git commit -m "git-fixup temporary commit" --quiet
if [ $? -ne 0 ]; then
  stderr "Failed to commit to index"
  exit 1
fi

deps=()
for dep in $(git deps --ignore-fixups $DEPFLAGS $LATEST); do
  if ! git merge-base --is-ancestor $dep $EARLIEST; then
    deps+=( $dep )
  elif [ $dep == $EARLIEST ]; then
    deps+=( $dep )
  fi
done

ndeps=${#deps[@]}
if [ $ndeps == 0 ]; then
  stderr "Index does not depend on any commit."
  stderr "Are you trying to amend a commit before the current branch?"
  git reset --soft 'HEAD^'
elif [ $ndeps != 1 ]; then  
  stderr "Index depends on multiple commits:"
  for d in "${deps[@]}"; do
    git log -n 1 --oneline $d
  done
  git reset --soft 'HEAD^'
else
  git commit --amend "--fixup=${deps}"
fi
